<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>

		<Title>Content Library</Title>
		<Description>A content-addressable data store. Content stores store codes by multihash and record their durable history in a story.</Description>
		<PackageTags>bigredprof;content-addressable;multihash;storage;stories</PackageTags>
		<Product>Content Library</Product>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BigRedProf.Data.Core" Version="0.8.0" />
		<PackageReference Include="BigRedProf.Stories.Core" Version="0.8.0" />
	</ItemGroup>

</Project>
